//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synapse.Databases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransactionsEntities : DbContext
    {
        public TransactionsEntities()
            : base("name=TransactionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TOrder> TOrders { get; set; }
        public virtual DbSet<TStrategy> TStrategies { get; set; }
        public virtual DbSet<TSubtotal> TSubtotals { get; set; }
        public virtual DbSet<TTrade> TTrades { get; set; }
    }
}
