//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synapse.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class TStrategy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TStrategy()
        {
            this.TOrders = new HashSet<TOrder>();
            this.TSubtotals = new HashSet<TSubtotal>();
            this.TStrategies1 = new HashSet<TStrategy>();
        }
    
        public int StrategyId { get; set; }
        public string Name { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.DateTime> CreationTime_ { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TOrder> TOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSubtotal> TSubtotals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TStrategy> TStrategies1 { get; set; }
        public virtual TStrategy TStrategy1 { get; set; }
    }
}
