//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synapse.Databases
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSubtotal
    {
        public int SubtotalId { get; set; }
        public System.DateTime Time { get; set; }
        public int StrategyId { get; set; }
        public decimal RealizedPnl { get; set; }
        public int Position { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual TStrategy TStrategy { get; set; }
    }
}
